class squishy_v1::xdebug (
  $xdebug_auto_trace = undef,
  $xdebug_cli_color = undef,
  $xdebug_collect_assignments = undef,
  $xdebug_collect_includes = undef,
  $xdebug_collect_params = undef,
  $xdebug_collect_return = undef,
  $xdebug_collect_vars = undef,
  $xdebug_coverage_enable = undef,
  $xdebug_default_enable = undef,
  $xdebug_dump_globals = undef,
  $xdebug_dump_once = undef,
  $xdebug_dump_undefined = undef,
  $xdebug_extended_info = undef,
  $xdebug_file_link_format = undef,
  $xdebug_idekey = undef,
  $xdebug_manual_url = undef,
  $xdebug_max_nesting_level = undef,
  $xdebug_overload_var_dump = undef,
  $xdebug_profiler_append = undef,
  $xdebug_profiler_enable = undef,
  $xdebug_profiler_enable_trigger = undef,
  $xdebug_profiler_output_dir = undef,
  $xdebug_profiler_output_name = undef,
  $xdebug_remote_autostart = undef,
  $xdebug_remote_connect_back = undef,
  $xdebug_remote_cookie_expire_time = undef,
  $xdebug_remote_enable = undef,
  $xdebug_remote_handler = undef,
  $xdebug_remote_host = undef,
  $xdebug_remote_log = undef,
  $xdebug_remote_mode = undef,
  $xdebug_remote_port = undef,
  $xdebug_scream = undef,
  $xdebug_show_exception_trace = undef,
  $xdebug_show_local_vars = undef,
  $xdebug_show_mem_delta = undef,
  $xdebug_trace_enable_trigger = undef,
  $xdebug_trace_format = undef,
  $xdebug_trace_options = undef,
  $xdebug_trace_output_dir = undef,
  $xdebug_trace_output_name = undef,
  $xdebug_var_display_max_children = undef,
  $xdebug_var_display_max_data = undef,
  $xdebug_var_display_max_depth = undef,
  ) {

  package { "php-pecl-xdebug":
    ensure => latest,
  }

  file { "/etc/php.d/xdebug.ini":
    content => template("squishy_v1/xdebug.ini.erb"),
    require => Package['php-pecl-xdebug'],
  }
}
